apiVersion: v1
kind: Service
metadata:
  name: checkout-frontend-service
  namespace: yummops-test
spec:
  selector:
    app: checkout-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
